import type { AndroidIconOutput, IosIconOutput, WebIconOutput } from "./types";

export const WEB_ICON_OUTPUTS: WebIconOutput[] = [
  { id: "favicon-16", label: "Favicon 16", width: 16, height: 16, fileName: "favicon-16x16.png" },
  { id: "favicon-32", label: "Favicon 32", width: 32, height: 32, fileName: "favicon-32x32.png" },
  { id: "favicon-48", label: "Favicon 48", width: 48, height: 48, fileName: "favicon-48x48.png" },
  { id: "apple-touch-180", label: "Apple Touch 180", width: 180, height: 180, fileName: "apple-touch-icon.png" },
  { id: "pwa-192", label: "PWA 192", width: 192, height: 192, fileName: "icon-192x192.png", purpose: "any" },
  { id: "pwa-512", label: "PWA 512", width: 512, height: 512, fileName: "icon-512x512.png", purpose: "any" },
  {
    id: "maskable-512",
    label: "Maskable 512",
    width: 512,
    height: 512,
    fileName: "maskable-icon-512x512.png",
    purpose: "maskable",
  },
];

export const ANDROID_ICON_OUTPUTS: AndroidIconOutput[] = [
  { id: "launcher-mdpi", label: "Launcher mdpi", density: "mdpi", width: 48, height: 48, directory: "mipmap-mdpi" },
  { id: "launcher-hdpi", label: "Launcher hdpi", density: "hdpi", width: 72, height: 72, directory: "mipmap-hdpi" },
  { id: "launcher-xhdpi", label: "Launcher xhdpi", density: "xhdpi", width: 96, height: 96, directory: "mipmap-xhdpi" },
  {
    id: "launcher-xxhdpi",
    label: "Launcher xxhdpi",
    density: "xxhdpi",
    width: 144,
    height: 144,
    directory: "mipmap-xxhdpi",
  },
  {
    id: "launcher-xxxhdpi",
    label: "Launcher xxxhdpi",
    density: "xxxhdpi",
    width: 192,
    height: 192,
    directory: "mipmap-xxxhdpi",
  },
];

export const IOS_ICON_OUTPUTS: IosIconOutput[] = [
  {
    id: "iphone-notification-2x",
    label: "iPhone Notification 2x",
    idiom: "iphone",
    size: "20x20",
    scale: "2x",
    width: 40,
    height: 40,
    fileName: "iphone-notification-20@2x.png",
  },
  {
    id: "iphone-notification-3x",
    label: "iPhone Notification 3x",
    idiom: "iphone",
    size: "20x20",
    scale: "3x",
    width: 60,
    height: 60,
    fileName: "iphone-notification-20@3x.png",
  },
  {
    id: "iphone-settings-2x",
    label: "iPhone Settings 2x",
    idiom: "iphone",
    size: "29x29",
    scale: "2x",
    width: 58,
    height: 58,
    fileName: "iphone-settings-29@2x.png",
  },
  {
    id: "iphone-settings-3x",
    label: "iPhone Settings 3x",
    idiom: "iphone",
    size: "29x29",
    scale: "3x",
    width: 87,
    height: 87,
    fileName: "iphone-settings-29@3x.png",
  },
  {
    id: "iphone-spotlight-2x",
    label: "iPhone Spotlight 2x",
    idiom: "iphone",
    size: "40x40",
    scale: "2x",
    width: 80,
    height: 80,
    fileName: "iphone-spotlight-40@2x.png",
  },
  {
    id: "iphone-spotlight-3x",
    label: "iPhone Spotlight 3x",
    idiom: "iphone",
    size: "40x40",
    scale: "3x",
    width: 120,
    height: 120,
    fileName: "iphone-spotlight-40@3x.png",
  },
  {
    id: "iphone-app-2x",
    label: "iPhone App 2x",
    idiom: "iphone",
    size: "60x60",
    scale: "2x",
    width: 120,
    height: 120,
    fileName: "iphone-app-60@2x.png",
  },
  {
    id: "iphone-app-3x",
    label: "iPhone App 3x",
    idiom: "iphone",
    size: "60x60",
    scale: "3x",
    width: 180,
    height: 180,
    fileName: "iphone-app-60@3x.png",
  },
  {
    id: "ipad-app-2x",
    label: "iPad App 2x",
    idiom: "ipad",
    size: "76x76",
    scale: "2x",
    width: 152,
    height: 152,
    fileName: "ipad-app-76@2x.png",
  },
  {
    id: "ipad-pro-app-2x",
    label: "iPad Pro App 2x",
    idiom: "ipad",
    size: "83.5x83.5",
    scale: "2x",
    width: 167,
    height: 167,
    fileName: "ipad-pro-app-83_5@2x.png",
  },
  {
    id: "app-store-1024",
    label: "App Store 1024",
    idiom: "ios-marketing",
    size: "1024x1024",
    scale: "1x",
    width: 1024,
    height: 1024,
    fileName: "ios-marketing-1024.png",
  },
];
